### ISSUE TITLE
Error running the sample example

### ISSUE THREAD

**Issue by ukamath** [pan5431333/pyoptree#6]
I installed using  pip and ran the test example and I get this error
day.kamath$ pip3 install pyoptree

Collecting pyoptree

  Downloading pyoptree-1.0.3-py3-none-any.whl (16 kB)

Requirement already satisfied: scikit-learn>=0.20.0 in /Users/uday.kamath/anaconda/lib/python3.6/site-packages (from pyoptree) (0.22)

Requirement already satisfied: numpy>=1.14.5 in /Users/uday.kamath/.local/lib/python3.6/site-packages (from pyoptree) (1.16.3)

Requirement already satisfied: tqdm>=4.26.0 in /Users/uday.kamath/.local/lib/python3.6/site-packages (from pyoptree) (4.43.0)

Requirement already satisfied: pandas>=0.23.1 in /Users/uday.kamath/.local/lib/python3.6/site-packages (from pyoptree) (1.0.2)

Requirement already satisfied: python-dateutil>=2.6.1 in /Users/uday.kamath/.local/lib/python3.6/site-packages (from pandas>=0.23.1->pyoptree) (2.8.1)

Requirement already satisfied: numpy>=1.14.5 in /Users/uday.kamath/.local/lib/python3.6/site-packages (from pyoptree) (1.16.3)

Requirement already satisfied: pytz>=2017.2 in /Users/uday.kamath/anaconda/lib/python3.6/site-packages (from pandas>=0.23.1->pyoptree) (2020.4)

Collecting pyomo>=5.5.0

  Downloading Pyomo-5.7.2.tar.gz (2.2 MB)

     |████████████████████████████████| 2.2 MB 2.1 MB/s 

Requirement already satisfied: ply in /Users/uday.kamath/anaconda/lib/python3.6/site-packages (from pyomo>=5.5.0->pyoptree) (3.10)

Requirement already satisfied: six>=1.4 in /Users/uday.kamath/anaconda/lib/python3.6/site-packages (from pyomo>=5.5.0->pyoptree) (1.15.0)

Requirement already satisfied: six>=1.4 in /Users/uday.kamath/anaconda/lib/python3.6/site-packages (from pyomo>=5.5.0->pyoptree) (1.15.0)

Collecting PyUtilib>=6.0.0

  Downloading PyUtilib-6.0.0-py2.py3-none-any.whl (254 kB)

     |████████████████████████████████| 254 kB 1.2 MB/s 

Requirement already satisfied: nose in /Users/uday.kamath/anaconda/lib/python3.6/site-packages (from PyUtilib>=6.0.0->pyomo>=5.5.0->pyoptree) (1.3.7)

Requirement already satisfied: six>=1.4 in /Users/uday.kamath/anaconda/lib/python3.6/site-packages (from pyomo>=5.5.0->pyoptree) (1.15.0)

Requirement already satisfied: numpy>=1.14.5 in /Users/uday.kamath/.local/lib/python3.6/site-packages (from pyoptree) (1.16.3)

Requirement already satisfied: joblib>=0.11 in /Users/uday.kamath/anaconda/lib/python3.6/site-packages (from scikit-learn>=0.20.0->pyoptree) (0.15.1)

Requirement already satisfied: scipy>=0.17.0 in /Users/uday.kamath/anaconda/lib/python3.6/site-packages (from scikit-learn>=0.20.0->pyoptree) (1.3.3)

Requirement already satisfied: numpy>=1.14.5 in /Users/uday.kamath/.local/lib/python3.6/site-packages (from pyoptree) (1.16.3)

Building wheels for collected packages: pyomo

  Building wheel for pyomo (setup.py) ... done

  Created wheel for pyomo: filename=Pyomo-5.7.2-cp36-cp36m-macosx_10_7_x86_64.whl size=4760595 sha256=3e0fc82ac555ac241603f54bed1f6790a5ed71ad4eb11ee47205ebcdf8c22ca5

  Stored in directory: /Users/uday.kamath/Library/Caches/pip/wheels/ae/de/0e/0893adcd8c006adef4a1ac338aab0bcfa55d0547b49f21927f

Successfully built pyomo

Installing collected packages: PyUtilib, pyomo, pyoptree

Successfully installed PyUtilib-6.0.0 pyomo-5.7.2 pyoptree-1.0.3

uday:OSDT uday.kamath$ python3

Python 3.6.1 |Continuum Analytics, Inc.| (default, May 11 2017, 13:04:09) 

[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin

Type "help", "copyright", "credits" or "license" for more information.

>>> from pyoptree.optree import OptimalHyperTreeModel, OptimalTreeModel

>>> import pandas as pd

>>> data = pd.DataFrame({

... "index": ['A', 'C', 'D', 'E', 'F'],

... "x1": [1, 2, 2, 2, 3],

... "x2": [1, 2, 1, 0, 1],

... "y": [1, 1, -1, -1, -1]

... })

>>> test_data = pd.DataFrame({

... "index": ['A', 'B', 'C', 'D', 'E', 'F', 'G'],

... "x1": [1, 1, 2, 2, 2, 3, 3],

... "x2": [1, 2, 2, 1, 0, 1, 0],

... "y": [1, 1, 1, -1, -1, -1, -1]

... })

>>> model = OptimalHyperTreeModel(["x1", "x2"], "y", tree_depth=2, N_min=1, alpha=0.1, solver_name="cplex")

>>> model.train(data)

Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

  File "/Users/uday.kamath/anaconda/lib/python3.6/site-packages/pyoptree/optree.py", line 762, in train

    warm_start, num_initialize_trees)

  File "/Users/uday.kamath/anaconda/lib/python3.6/site-packages/pyoptree/optree.py", line 56, in train

    self.fast_train(data, num_initialize_trees)

  File "/Users/uday.kamath/anaconda/lib/python3.6/site-packages/pyoptree/optree.py", line 131, in fast_train

    train_x = data.ix[::, self.P_range].values

  File "/Users/uday.kamath/.local/lib/python3.6/site-packages/pandas/core/generic.py", line 5274, in __getattr__

    return object.__getattribute__(self, name)

AttributeError: 'DataFrame' object has no attribute 'ix'

**Comment by koftezz** [comment]
@ukamath `.ix` is [deprecated](https://pandas.pydata.org/pandas-docs/version/1.0.0/whatsnew/v1.0.0.html#removal-of-prior-version-deprecations-changes). You can manually update the code with `.iloc`.

**Comment by nachoarevans** [comment]
I have had the same problem. Could you solve it??
